version: "3.9"
services:
  web:
    restart: always
    build: .
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    command:  "django-admin runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - 80:80

