version: "3.9"
services:
  web:
    restart: always
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    command:  "django-admin runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - 80:80

