volumes:
  static:
    name: static

services:

  django:
    image: compose-django-blog:latest
    build:
      context: ..
      dockerfile: Dockerfile
    expose: 
      - 8000
    volumes:
      - "static:/static"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - PYTHONPATH=/app
      - PATH="${PATH}:/home/python/.local/bin"
    
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "static:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:z"
    depends_on:
      - django

